# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(618, 479)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(330, 520, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setObjectName("buttonBox")
        self.start = QtWidgets.QPushButton(Dialog)
        self.start.setGeometry(QtCore.QRect(20, 10, 81, 41))
        self.start.setObjectName("start")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 80, 91, 31))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(510, 440, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 10, 81, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(240, 80, 61, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 120, 100, 100))
        self.pushButton_5.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_5.setAccessibleDescription("")
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color:rgb(255,0,0);\n"
"color:white;\n"
"brorder-radius:50px;\n"
"border:2px groove gray;\n"
"border-style:outset;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(160, 90, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(340, 90, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(230, 120, 100, 100))
        self.pushButton_6.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_6.setAccessibleDescription("")
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color:rgb(255,0,0);\n"
"color:white;\n"
"brorder-radius:50px;\n"
"border:2px groove gray;\n"
"border-style:outset;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(400, 120, 100, 100))
        self.pushButton_7.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_7.setAccessibleDescription("")
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color:rgb(255,0,0);\n"
"color:white;\n"
"brorder-radius:50px;\n"
"border:2px groove gray;\n"
"border-style:outset;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(500, 90, 69, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(160, 60, 69, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(1, "")
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(340, 60, 69, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.pushButton.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.start.setText(_translate("Dialog", "start"))
        self.label.setText(_translate("Dialog", "灯运行了："))
        self.pushButton.setText(_translate("Dialog", "关闭窗口"))
        self.pushButton_2.setText(_translate("Dialog", "暂停"))
        self.label_2.setText(_translate("Dialog", "灯运行了："))
        self.pushButton_5.setText(_translate("Dialog", "灯还有0秒"))
        self.comboBox.setItemText(0, _translate("Dialog", "绿灯"))
        self.comboBox.setItemText(1, _translate("Dialog", "红灯"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "绿灯"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "红灯"))
        self.pushButton_6.setText(_translate("Dialog", "灯还有0秒"))
        self.pushButton_7.setText(_translate("Dialog", "灯还有0秒"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "红灯"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "绿灯"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "左转"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "直行"))
