# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def canshu(self):
        self.first_light=
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(618, 479)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(330, 520, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setObjectName("buttonBox")
        self.start_box = QtWidgets.QPushButton(Dialog)
        self.start_box.setGeometry(QtCore.QRect(20, 10, 81, 41))
        self.start_box.setObjectName("start_box")
        self.left_light_label = QtWidgets.QLabel(Dialog)
        self.left_light_label.setGeometry(QtCore.QRect(20, 80, 91, 31))
        self.left_light_label.setObjectName("left_light_label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(510, 440, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.zanting_box = QtWidgets.QPushButton(Dialog)
        self.zanting_box.setGeometry(QtCore.QRect(120, 10, 81, 41))
        self.zanting_box.setObjectName("zanting_box")
        self.mid_light_label = QtWidgets.QLabel(Dialog)
        self.mid_light_label.setGeometry(QtCore.QRect(240, 80, 61, 31))
        self.mid_light_label.setObjectName("mid_light_label")
        self.left_lightbox = QtWidgets.QPushButton(Dialog)
        self.left_lightbox.setGeometry(QtCore.QRect(60, 120, 100, 100))
        self.left_lightbox.setMaximumSize(QtCore.QSize(100, 100))
        self.left_lightbox.setAccessibleDescription("")
        self.left_lightbox.setStyleSheet("QPushButton{\n"
"background-color:rgb(255,0,0);\n"
"color:white;\n"
"brorder-radius:50px;\n"
"border:2px groove gray;\n"
"border-style:outset;\n"
"}")
        self.left_lightbox.setObjectName("left_lightbox")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(160, 90, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(340, 90, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.mid_lightbox = QtWidgets.QPushButton(Dialog)
        self.mid_lightbox.setGeometry(QtCore.QRect(230, 120, 100, 100))
        self.mid_lightbox.setMaximumSize(QtCore.QSize(100, 100))
        self.mid_lightbox.setAccessibleDescription("")
        self.mid_lightbox.setStyleSheet("QPushButton{\n"
"background-color:rgb(255,0,0);\n"
"color:white;\n"
"brorder-radius:50px;\n"
"border:2px groove gray;\n"
"border-style:outset;\n"
"}")
        self.mid_lightbox.setObjectName("mid_lightbox")
        self.right_lightbox = QtWidgets.QPushButton(Dialog)
        self.right_lightbox.setGeometry(QtCore.QRect(400, 120, 100, 100))
        self.right_lightbox.setMaximumSize(QtCore.QSize(100, 100))
        self.right_lightbox.setAccessibleDescription("")
        self.right_lightbox.setStyleSheet("QPushButton{\n"
"background-color:rgb(255,0,0);\n"
"color:white;\n"
"brorder-radius:50px;\n"
"border:2px groove gray;\n"
"border-style:outset;\n"
"}")
        self.right_lightbox.setObjectName("right_lightbox")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(500, 90, 69, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(160, 60, 69, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(2, "")
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(340, 60, 69, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(500, 60, 69, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.right_light_label = QtWidgets.QLabel(Dialog)
        self.right_light_label.setGeometry(QtCore.QRect(420, 80, 61, 31))
        self.right_light_label.setObjectName("right_light_label")
        self.shuxing = QtWidgets.QLabel(Dialog)
        self.shuxing.setGeometry(QtCore.QRect(340, 250, 81, 41))
        self.shuxing.setObjectName("shuxing")
        self.change_left = QtWidgets.QTextEdit(Dialog)
        self.change_left.setGeometry(QtCore.QRect(420, 260, 101, 31))
        self.change_left.setObjectName("change_left")
        self.change_mid = QtWidgets.QTextEdit(Dialog)
        self.change_mid.setGeometry(QtCore.QRect(420, 300, 101, 31))
        self.change_mid.setObjectName("change_mid")
        self.change_right = QtWidgets.QTextEdit(Dialog)
        self.change_right.setGeometry(QtCore.QRect(420, 340, 101, 31))
        self.change_right.setObjectName("change_right")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(540, 280, 51, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.light_switch = QtWidgets.QComboBox(Dialog)
        self.light_switch.setGeometry(QtCore.QRect(250, 10, 101, 41))
        self.light_switch.setObjectName("light_switch")
        self.light_switch.addItem("")
        self.light_switch.addItem("")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.pushButton.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.start_box.setText(_translate("Dialog", "start"))
        self.left_light_label.setText(_translate("Dialog", "灯运行了："))
        self.pushButton.setText(_translate("Dialog", "关闭窗口"))
        self.zanting_box.setText(_translate("Dialog", "暂停"))
        self.mid_light_label.setText(_translate("Dialog", "灯运行了："))
        self.left_lightbox.setText(_translate("Dialog", "灯还有0秒"))
        self.comboBox.setItemText(0, _translate("Dialog", "绿灯"))
        self.comboBox.setItemText(1, _translate("Dialog", "红灯"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "绿灯"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "红灯"))
        self.mid_lightbox.setText(_translate("Dialog", "灯还有0秒"))
        self.right_lightbox.setText(_translate("Dialog", "灯还有0秒"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "绿灯"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "红灯"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "空"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "左转"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "直行"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "空"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "直行"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "右转"))
        self.right_light_label.setText(_translate("Dialog", "灯运行了："))
        self.shuxing.setText(_translate("Dialog", "属性值更改："))
        self.pushButton_5.setText(_translate("Dialog", "提交"))
        self.light_switch.setItemText(0, _translate("Dialog", "第一个红绿灯"))
        self.light_switch.setItemText(1, _translate("Dialog", "第二个红绿灯"))
import image_rc
